#ifndef _AM335X_GPIO_H_
#define _AM335X_GPIO_H_

#include "AM335X_Mapping.h"


/**GPIO0**/
#define         GPIO0_REVISION				(*(volatile unsigned long *)(GPIO0_BASE + 0x0  ))
#define         GPIO0_SYSCONFIG             (*(volatile unsigned long *)(GPIO0_BASE + 0x10 ))
#define         GPIO0_EOI                   (*(volatile unsigned long *)(GPIO0_BASE + 0x20 ))
#define         GPIO0_IRQSTATUS_RAW_0       (*(volatile unsigned long *)(GPIO0_BASE + 0x24 ))
#define         GPIO0_IRQSTATUS_RAW_1       (*(volatile unsigned long *)(GPIO0_BASE + 0x28 ))
#define         GPIO0_IRQSTATUS_0           (*(volatile unsigned long *)(GPIO0_BASE + 0x2C ))
#define         GPIO0_IRQSTATUS_1           (*(volatile unsigned long *)(GPIO0_BASE + 0x30 ))
#define         GPIO0_IRQSTATUS_SET_0       (*(volatile unsigned long *)(GPIO0_BASE + 0x34 ))
#define         GPIO0_IRQSTATUS_SET_1       (*(volatile unsigned long *)(GPIO0_BASE + 0x38 ))
#define         GPIO0_IRQSTATUS_CLR_0       (*(volatile unsigned long *)(GPIO0_BASE + 0x3C ))
#define         GPIO0_IRQSTATUS_CLR_1       (*(volatile unsigned long *)(GPIO0_BASE + 0x40 ))
#define         GPIO0_IRQWAKEN_0            (*(volatile unsigned long *)(GPIO0_BASE + 0x44 ))
#define         GPIO0_IRQWAKEN_1            (*(volatile unsigned long *)(GPIO0_BASE + 0x48 ))
#define         GPIO0_SYSSTATUS             (*(volatile unsigned long *)(GPIO0_BASE + 0x114))
#define         GPIO0_CTRL                  (*(volatile unsigned long *)(GPIO0_BASE + 0x130))
#define         GPIO0_OE                    (*(volatile unsigned long *)(GPIO0_BASE + 0x134))
#define         GPIO0_DATAIN                (*(volatile unsigned long *)(GPIO0_BASE + 0x138))
#define         GPIO0_DATAOUT               (*(volatile unsigned long *)(GPIO0_BASE + 0x13C))
#define         GPIO0_LEVELDETECT0          (*(volatile unsigned long *)(GPIO0_BASE + 0x140))
#define         GPIO0_LEVELDETECT1          (*(volatile unsigned long *)(GPIO0_BASE + 0x144))
#define         GPIO0_RISINGDETECT          (*(volatile unsigned long *)(GPIO0_BASE + 0x148))
#define         GPIO0_FALLINGDETECT         (*(volatile unsigned long *)(GPIO0_BASE + 0x14C))
#define         GPIO0_DEBOUNCENABLE         (*(volatile unsigned long *)(GPIO0_BASE + 0x150))
#define         GPIO0_DEBOUNCINGTIME        (*(volatile unsigned long *)(GPIO0_BASE + 0x154))
#define         GPIO0_CLEARDATAOUT          (*(volatile unsigned long *)(GPIO0_BASE + 0x190))
#define         GPIO0_SETDATAOUT            (*(volatile unsigned long *)(GPIO0_BASE + 0x194))

/*GPIO1*/
#define         GPIO1_REVISION				(*(volatile unsigned long *)(GPIO1_BASE + 0x0  ))
#define         GPIO1_SYSCONFIG             (*(volatile unsigned long *)(GPIO1_BASE + 0x10 ))
#define         GPIO1_EOI                   (*(volatile unsigned long *)(GPIO1_BASE + 0x20 ))
#define         GPIO1_IRQSTATUS_RAW_0       (*(volatile unsigned long *)(GPIO1_BASE + 0x24 ))
#define         GPIO1_IRQSTATUS_RAW_1       (*(volatile unsigned long *)(GPIO1_BASE + 0x28 ))
#define         GPIO1_IRQSTATUS_0           (*(volatile unsigned long *)(GPIO1_BASE + 0x2C ))
#define         GPIO1_IRQSTATUS_1           (*(volatile unsigned long *)(GPIO1_BASE + 0x30 ))
#define         GPIO1_IRQSTATUS_SET_0       (*(volatile unsigned long *)(GPIO1_BASE + 0x34 ))
#define         GPIO1_IRQSTATUS_SET_1       (*(volatile unsigned long *)(GPIO1_BASE + 0x38 ))
#define         GPIO1_IRQSTATUS_CLR_0       (*(volatile unsigned long *)(GPIO1_BASE + 0x3C ))
#define         GPIO1_IRQSTATUS_CLR_1       (*(volatile unsigned long *)(GPIO1_BASE + 0x40 ))
#define         GPIO1_IRQWAKEN_0            (*(volatile unsigned long *)(GPIO1_BASE + 0x44 ))
#define         GPIO1_IRQWAKEN_1            (*(volatile unsigned long *)(GPIO1_BASE + 0x48 ))
#define         GPIO1_SYSSTATUS             (*(volatile unsigned long *)(GPIO1_BASE + 0x114))
#define         GPIO1_CTRL                  (*(volatile unsigned long *)(GPIO1_BASE + 0x130))
#define         GPIO1_OE                    (*(volatile unsigned long *)(GPIO1_BASE + 0x134))
#define         GPIO1_DATAIN                (*(volatile unsigned long *)(GPIO1_BASE + 0x138))
#define         GPIO1_DATAOUT               (*(volatile unsigned long *)(GPIO1_BASE + 0x13C))
#define         GPIO1_LEVELDETECT0          (*(volatile unsigned long *)(GPIO1_BASE + 0x140))
#define         GPIO1_LEVELDETECT1          (*(volatile unsigned long *)(GPIO1_BASE + 0x144))
#define         GPIO1_RISINGDETECT          (*(volatile unsigned long *)(GPIO1_BASE + 0x148))
#define         GPIO1_FALLINGDETECT         (*(volatile unsigned long *)(GPIO1_BASE + 0x14C))
#define         GPIO1_DEBOUNCENABLE         (*(volatile unsigned long *)(GPIO1_BASE + 0x150))
#define         GPIO1_DEBOUNCINGTIME        (*(volatile unsigned long *)(GPIO1_BASE + 0x154))
#define         GPIO1_CLEARDATAOUT          (*(volatile unsigned long *)(GPIO1_BASE + 0x190))
#define         GPIO1_SETDATAOUT            (*(volatile unsigned long *)(GPIO1_BASE + 0x194))


/*GPIO2*/
#define         GPIO2_REVISION				(*(volatile unsigned long *)(GPIO2_BASE + 0x0  ))
#define         GPIO2_SYSCONFIG             (*(volatile unsigned long *)(GPIO2_BASE + 0x10 ))
#define         GPIO2_EOI                   (*(volatile unsigned long *)(GPIO2_BASE + 0x20 ))
#define         GPIO2_IRQSTATUS_RAW_0       (*(volatile unsigned long *)(GPIO2_BASE + 0x24 ))
#define         GPIO2_IRQSTATUS_RAW_1       (*(volatile unsigned long *)(GPIO2_BASE + 0x28 ))
#define         GPIO2_IRQSTATUS_0           (*(volatile unsigned long *)(GPIO2_BASE + 0x2C ))
#define         GPIO2_IRQSTATUS_1           (*(volatile unsigned long *)(GPIO2_BASE + 0x30 ))
#define         GPIO2_IRQSTATUS_SET_0       (*(volatile unsigned long *)(GPIO2_BASE + 0x34 ))
#define         GPIO2_IRQSTATUS_SET_1       (*(volatile unsigned long *)(GPIO2_BASE + 0x38 ))
#define         GPIO2_IRQSTATUS_CLR_0       (*(volatile unsigned long *)(GPIO2_BASE + 0x3C ))
#define         GPIO2_IRQSTATUS_CLR_1       (*(volatile unsigned long *)(GPIO2_BASE + 0x40 ))
#define         GPIO2_IRQWAKEN_0            (*(volatile unsigned long *)(GPIO2_BASE + 0x44 ))
#define         GPIO2_IRQWAKEN_1            (*(volatile unsigned long *)(GPIO2_BASE + 0x48 ))
#define         GPIO2_SYSSTATUS             (*(volatile unsigned long *)(GPIO2_BASE + 0x114))
#define         GPIO2_CTRL                  (*(volatile unsigned long *)(GPIO2_BASE + 0x130))
#define         GPIO2_OE                    (*(volatile unsigned long *)(GPIO2_BASE + 0x134))
#define         GPIO2_DATAIN                (*(volatile unsigned long *)(GPIO2_BASE + 0x138))
#define         GPIO2_DATAOUT               (*(volatile unsigned long *)(GPIO2_BASE + 0x13C))
#define         GPIO2_LEVELDETECT0          (*(volatile unsigned long *)(GPIO2_BASE + 0x140))
#define         GPIO2_LEVELDETECT1          (*(volatile unsigned long *)(GPIO2_BASE + 0x144))
#define         GPIO2_RISINGDETECT          (*(volatile unsigned long *)(GPIO2_BASE + 0x148))
#define         GPIO2_FALLINGDETECT         (*(volatile unsigned long *)(GPIO2_BASE + 0x14C))
#define         GPIO2_DEBOUNCENABLE         (*(volatile unsigned long *)(GPIO2_BASE + 0x150))
#define         GPIO2_DEBOUNCINGTIME        (*(volatile unsigned long *)(GPIO2_BASE + 0x154))
#define         GPIO2_CLEARDATAOUT          (*(volatile unsigned long *)(GPIO2_BASE + 0x190))
#define         GPIO2_SETDATAOUT            (*(volatile unsigned long *)(GPIO2_BASE + 0x194))


/*GPIO3*/
#define         GPIO3_REVISION				(*(volatile unsigned long *)(GPIO3_BASE + 0x0  ))
#define         GPIO3_SYSCONFIG             (*(volatile unsigned long *)(GPIO3_BASE + 0x10 ))
#define         GPIO3_EOI                   (*(volatile unsigned long *)(GPIO3_BASE + 0x20 ))
#define         GPIO3_IRQSTATUS_RAW_0       (*(volatile unsigned long *)(GPIO3_BASE + 0x24 ))
#define         GPIO3_IRQSTATUS_RAW_1       (*(volatile unsigned long *)(GPIO3_BASE + 0x28 ))
#define         GPIO3_IRQSTATUS_0           (*(volatile unsigned long *)(GPIO3_BASE + 0x2C ))
#define         GPIO3_IRQSTATUS_1           (*(volatile unsigned long *)(GPIO3_BASE + 0x30 ))
#define         GPIO3_IRQSTATUS_SET_0       (*(volatile unsigned long *)(GPIO3_BASE + 0x34 ))
#define         GPIO3_IRQSTATUS_SET_1       (*(volatile unsigned long *)(GPIO3_BASE + 0x38 ))
#define         GPIO3_IRQSTATUS_CLR_0       (*(volatile unsigned long *)(GPIO3_BASE + 0x3C ))
#define         GPIO3_IRQSTATUS_CLR_1       (*(volatile unsigned long *)(GPIO3_BASE + 0x40 ))
#define         GPIO3_IRQWAKEN_0            (*(volatile unsigned long *)(GPIO3_BASE + 0x44 ))
#define         GPIO3_IRQWAKEN_1            (*(volatile unsigned long *)(GPIO3_BASE + 0x48 ))
#define         GPIO3_SYSSTATUS             (*(volatile unsigned long *)(GPIO3_BASE + 0x114))
#define         GPIO3_CTRL                  (*(volatile unsigned long *)(GPIO3_BASE + 0x130))
#define         GPIO3_OE                    (*(volatile unsigned long *)(GPIO3_BASE + 0x134))
#define         GPIO3_DATAIN                (*(volatile unsigned long *)(GPIO3_BASE + 0x138))
#define         GPIO3_DATAOUT               (*(volatile unsigned long *)(GPIO3_BASE + 0x13C))
#define         GPIO3_LEVELDETECT0          (*(volatile unsigned long *)(GPIO3_BASE + 0x140))
#define         GPIO3_LEVELDETECT1          (*(volatile unsigned long *)(GPIO3_BASE + 0x144))
#define         GPIO3_RISINGDETECT          (*(volatile unsigned long *)(GPIO3_BASE + 0x148))
#define         GPIO3_FALLINGDETECT         (*(volatile unsigned long *)(GPIO3_BASE + 0x14C))
#define         GPIO3_DEBOUNCENABLE         (*(volatile unsigned long *)(GPIO3_BASE + 0x150))
#define         GPIO3_DEBOUNCINGTIME        (*(volatile unsigned long *)(GPIO3_BASE + 0x154))
#define         GPIO3_CLEARDATAOUT          (*(volatile unsigned long *)(GPIO3_BASE + 0x190))
#define         GPIO3_SETDATAOUT            (*(volatile unsigned long *)(GPIO3_BASE + 0x194))


#endif

